sonar.projectKey=employee-system
sonar.projectName=employee-system

# chỉ scan code backend
sonar.sources=backend/src

# chỉ scan test backend
sonar.tests=backend/src/tests

# chỉ nhận file test
sonar.test.inclusions=backend/src/tests/**/*.test.js

# đọc coverage từ jest
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# bỏ coverage các file bootstrap
sonar.coverage.exclusions=\
backend/src/server.js,\
backend/src/app.js,\
backend/src/middleware/**

# bỏ scan hoàn toàn
sonar.exclusions=\
node_modules/**,\
dist/**,\
build/**,\
backend/src/server.js,\
backend/src/app.js

sonar.sourceEncoding=UTF-8