server {
    listen 80;
    server_name tqa-test.deha.vn;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name tqa-test.deha.vn;

    ssl_certificate /etc/letsencrypt/live/tqa-test.deha.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tqa-test.deha.vn/privkey.pem;

    location / {
        proxy_pass http://localhost:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}